<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Shopee\Helper\Data');
$count_item         = count($_productCollection);
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */
			echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?php
	$viewMode        = 'grid';
	$image           = 'category_page_list_slider';
	$showDescription = false;
	$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$showWishlist    = true;
	$showCompare     = true;
	$showCart        = true;
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos    = $block->getPositioned();
	$tag_id = "sm_filterproducts_" . time() . rand() . "";
	?>

	<?php if (!empty($this->_getConfig('title_module'))) { ?>
        <div class="title-block-list">
		<h2><?php echo $this->_getConfig('title_module'); ?></h2>
	</div>
	<?php } ?>


    <div id="<?php echo $tag_id; ?>" class="products-type-list">
		<?php
		if ($this->_getConfig('product_source') == 'countdown_products') {
			$dateTo = $this->_getConfig('date_to', '');
			?>
            <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
			<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
		</div>
		<?php } ?>

        <div class="owl-carousel owl-theme">
			<?php /** @var $_product \Magento\Catalog\Model\Product */
			$j       = 0;
			$count   = 0;
			$nb_rows = $this->_getConfig('row');
			?>
			<?php foreach ($_productCollection as $_product):
				$count++;
				$j++;
				?>
				<?php if ($count % $nb_rows == 1 || $nb_rows == 1) { ?>
                <div class="item product product-item">
			<?php } ?>
                <div class="item-inner clearfix">
						<?php
						$productImage = $block->getImage($_product, $image);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>

					<?php // Product Image 
					?>
                    <div class="box-image">
							<a href="<?php /* @escapeNotVerified */
							echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>							
						</div>

					<?php
					if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
						$specialToDate = $_product->getSpecialToDate();
						?>
                        <div class="deals-countdown clearfix" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
								<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
							</div>
					<?php } ?>

                    <div class="product details product-item-details box-info">
							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
                        <h2 class="product name product-item-name product-name">
								<a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
								   echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */
									echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h2>

						<?php /* @escapeNotVerified */
						echo $block->getProductPrice($_product) ?>
						<?php echo $block->getProductDetailsHtml($_product); ?>
						<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
						</div>
					</div>
				<?php if (($count % $nb_rows == 0 || $count == $count_item)) { ?>
                </div>
			<?php } ?>
			<?php endforeach; ?>
		</div>
	</div>

    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            var $element = $('#<?php echo $tag_id ?>');

            function CountDown(date, id) {
                dateNow = new Date();
                amount = date.getTime() - dateNow.getTime();
                delete dateNow;
                if (amount < 0) {
                    id.html("Now!");
                } else {
                    days = 0;
                    hours = 0;
                    mins = 0;
                    secs = 0;
                    out = "";
                    amount = Math.floor(amount / 1000);
                    days = Math.floor(amount / 86400);
                    amount = amount % 86400;
                    hours = Math.floor(amount / 3600);
                    amount = amount % 3600;
                    mins = Math.floor(amount / 60);
                    amount = amount % 60;
                    secs = Math.floor(amount);
                    $(".time-day .num-time", id).text(days);
                    $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('D')?>" : "<?php echo __('D')?>"));
                    $(".time-hours .num-time", id).text(hours);
                    $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('H')?>" : "<?php echo __('H')?>"));
                    $(".time-mins .num-time", id).text(mins);
                    $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('M')?>" : "<?php echo __('M')?>"));
                    $(".time-secs .num-time", id).text(secs);
                    $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('S')?>" : "<?php echo __('S')?>"));
                    setTimeout(function () {
                        CountDown(date, id)
                    }, 1000);
                }
            }

            $(".deals-countdown", $element).each(function () {
                var timer = $(this).data('timer');
                var data = new Date(timer);
                CountDown(data, $(this));
            });
        });
    </script>
	<?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
	<?php endif; ?>
<?php endif; ?>
