<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$count_item         = count($_productCollection);
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Shopee\Helper\Data');
$lthelper           = $this->helper('Sm\FilterProducts\Helper\Data');
$thumbLimit         = 4; //$this->_getConfig('thumb_limit');

$enableLadyLoading = 0;
$mediaSrc          = $_config->getMediaUrl();
if ($enableLadyLoading) {
	$imgClass = 'lazyload';
} else {
	$imgClass = '';
}
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */
			echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?php
	$viewMode        = 'grid';
	$image           = 'category_page_grid';
	$showDescription = false;
	$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$showWishlist    = true;
	$showCompare     = true;
	$showCart        = true;
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos    = $block->getPositioned();
	$tag_id = "sm_filterproducts_" . time() . rand() . "";
	?>


    <div id="<?php echo $tag_id; ?>" class="products-grid">
		<?php if (!empty($this->_getConfig('title_module'))) { ?>
            <div class="title-block">
				<h2><?php echo $this->_getConfig('title_module'); ?></h2>
			</div>
		<?php } ?>

		<?php
		if ($this->_getConfig('product_source') == 'countdown_products') {
			$dateTo = $this->_getConfig('date_to', '');
			?>
            <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
			<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
			<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
		</div>
		<?php } ?>

        <div class="row grid-deal-container">
			<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			<?php foreach ($_productCollection as $_product): ?>
				<?php
				$productInfo = "product_" . rand() . time();
				?>
                <div class="item product product-item col-lg-4 col-md-4 col-4">
					<div class="item-inner clearfix <?php echo $productInfo; ?>">
						
						<div class="product-content">
							<?php
							$productImage = $block->getImage($_product, $image);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>

							<?php // Product Image ?>
                            <div class="image-thumbs ">
								<div class="box-image">
									<a href="<?php /* @escapeNotVerified */
									echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php echo $productImage->toHtml(); ?>
									</a>

                                    <!--LABEL PRODUCT-->
									<?php
									$orgprice             = $_product->getPrice();
									$specialprice         = $_product->getSpecialPrice();
									$specialPriceFromDate = $_product->getSpecialFromDate();
									$specialPriceToDate   = $_product->getSpecialToDate();
									$today                = time();

									if ($specialprice && $_config->getAdvanced('show_salelabel')) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
											<?php if ($specialprice < $orgprice) {
												$save_percent = 100 - round(($specialprice / $orgprice) * 100);
												?>
                                                <div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php echo '-' . $save_percent . '%'; ?>
												</span>
											</div>
											<?php } ?>
										<?php }
									}
									?>

									<?php
									$now      = date("Y-m-d");
									$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
									$newsTo   = substr($_product->getNewsToDate(), 0, 10);

									if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                            <div class="label-product label-new">
													<span class="new-product-icon"><?php echo __('New'); ?></span>
												</div>
										<?php }
									} ?>
                                    <!--END LABEL PRODUCT-->
									
									<div class="bottom-action">
										<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
												echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
													echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @escapeNotVerified */
													echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
													echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary btn-action btn-cart">
														<span><?php /* @escapeNotVerified */
															echo __('Add to Cart') ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
															echo __('In stock') ?></span></div>
												<?php else: ?>
                                                    <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
															echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										<?php } ?>

										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                            <a href="#"
                                               data-post='<?php /* @escapeNotVerified */
											   echo $block->getAddToWishlistParams($_product); ?>'
                                               class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist"
                                               title="<?php /* @escapeNotVerified */
											   echo __('Add to Wish List') ?>">
												<span><?php /* @escapeNotVerified */
													echo __('Add to Wish List') ?></span>
											</a>
										<?php endif; ?>
										<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
											<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                            <a href="#" class="action tocompare btn-action link-compare"
                                               data-post='<?php /* @escapeNotVerified */
											   echo $compareHelper->getPostDataParams($_product); ?>'
                                               title="<?php /* @escapeNotVerified */
											   echo __('Add to Compare') ?>">
												<span><?php /* @escapeNotVerified */
													echo __('Add to Compare') ?></span>
											</a>
										<?php endif; ?>
									</div>
								</div>
							</div>

							<?php
							if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
								$specialToDate = $_product->getSpecialToDate();
								?>
                                <div class="deals-countdown clearfix" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
									<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
									<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
									<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
									<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
								</div>
							<?php } ?>

                            <div class="product details product-item-details box-info">
								<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
                                <h2 class="product name product-item-name product-name">
									<a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */
									   echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */
										echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h2>

								<?php /* @escapeNotVerified */
								echo $block->getProductPrice($_product) ?>
								<?php echo $block->getProductDetailsHtml($_product); ?>
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
							</div>
						</div>
						
						<div class="slider-thumbs">
							<div class="thumbs-product">
								<?php
								$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
								$product       = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
								$images        = $product->getMediaGalleryImages();
								$limit         = 0;

								foreach ($images as $child) {
									$limit++;
									if ($limit <= $thumbLimit) {
										$img = $lthelper->_getImageThumbnail($child->getData('file'));
										if (!empty($img) && isset($img[0])) {
											$big_image_config   = [
												'width'      => 300,
												'height'     => 300,
												'background' => '#ffffff',
												'function'   => 1
											];
											$small_image_config = [
												'width'      => 120,
												'height'     => 120,
												'background' => '#ffffff',
												'function'   => 1
											];
											$resizedImageBig    = $lthelper->_resizeImage($img[0], $big_image_config, 'product');
											$resizedImageUrl    = $lthelper->_resizeImage($img[0], $small_image_config, 'product'); ?>
                                            <div class="item-img" data-src="<?php echo $resizedImageBig; ?>">
												<img class="<?php echo $imgClass; ?>"
													<?php if ($enableLadyLoading) { ?>
                                                        src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                        data-src="<?php echo $resizedImageUrl; ?>"
													<?php } else { ?>
                                                        src="<?php echo $resizedImageUrl; ?>"
													<?php } ?>

                                                     alt="image"/>
											
											</div>
											<?php
										}
									}
								} ?>
							</div>
						</div>

						<script type="text/javascript">
							require([
                                'jquery',
                                'slick'
                            ], function ($) {
                                $('.<?php echo $productInfo; ?> .thumbs-product').slick({
                                    dots: false,
                                    vertical: true,
                                    slidesToShow: 3,
                                    prevArrow: '<div class="slick-prev" aria-label="Previous"><span>Previous</span></div>',
                                    nextArrow: '<div class="slick-next" aria-label="Next"><span>Next</span></div>'
                                });

                                $(".<?php echo $productInfo;?> .thumbs-product .item-img").click(function () {
                                    $(".<?php echo $productInfo;?> .thumbs-product .item-img").removeClass('thumb-active');
                                    $(this).addClass('thumb-active');
                                    var thumb_src = $(this).attr("data-src");
                                    $(".<?php echo $productInfo;?> .box-image a img").attr("src", thumb_src);
                                });
                            });
						</script>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</div>


    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            var $element = $('#<?php echo $tag_id ?>');

            function CountDown(date, id) {
                dateNow = new Date();
                amount = date.getTime() - dateNow.getTime();
                delete dateNow;
                if (amount < 0) {
                    id.html("Now!");
                } else {
                    days = 0;
                    hours = 0;
                    mins = 0;
                    secs = 0;
                    out = "";
                    amount = Math.floor(amount / 1000);
                    days = Math.floor(amount / 86400);
                    amount = amount % 86400;
                    hours = Math.floor(amount / 3600);
                    amount = amount % 3600;
                    mins = Math.floor(amount / 60);
                    amount = amount % 60;
                    secs = Math.floor(amount);
                    $(".time-day .num-time", id).text(days);
                    $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day')?>" : "<?php echo __('Days')?>"));
                    $(".time-hours .num-time", id).text(hours);
                    $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour')?>" : "<?php echo __('Hours')?>"));
                    $(".time-mins .num-time", id).text(mins);
                    $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min')?>" : "<?php echo __('Mins')?>"));
                    $(".time-secs .num-time", id).text(secs);
                    $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec')?>" : "<?php echo __('Secs')?>"));
                    setTimeout(function () {
                        CountDown(date, id)
                    }, 1000);
                }
            }

            $(".deals-countdown", $element).each(function () {
                var timer = $(this).data('timer');
                var data = new Date(timer);
                CountDown(data, $(this));
            });
        });
    </script>
	<?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
	<?php endif; ?>
<?php endif; ?>
